# Generated by Django 3.0.5 on 2020-04-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=31.5, max_digits=100)),
                ('discount_price', models.DecimalField(decimal_places=2, default=31.5, max_digits=100)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('img', models.ImageField(upload_to='', verbose_name='Image Of Product')),
                ('category', models.CharField(choices=[('men', 'men'), ('women', 'women'), ('Kids', 'kids'), ('accessories', 'accessories')], max_length=50)),
            ],
        ),
    ]
