# Generated by Django 3.0.5 on 2020-05-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20200501_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(default=880, max_length=50),
            preserve_default=False,
        ),
    ]
