# Generated by Django 3.0.5 on 2020-05-03 17:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_shippingaddress_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=200, null=True, unique=True),
        ),
    ]
